name: dr_words
description: A new Flutter project.
scripts:
  runner: flutter pub run build_runner build --delete-conflicting-outputs
  runner-watch: flutter pub run build_runner watch --delete-conflicting-outputs

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^4.0.4
  flutter_bloc: ^6.0.1
  rxdart: ^0.24.1
  async: ^2.4.1
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  # For OS-specific directory paths
  shared_preferences: ^0.5.8
  shared_preferences_web: ^0.1.2+7
  injectable: ^1.0.4
  flutter_svg: ^0.17.4
  auto_route: ^0.6.7
  freezed_annotation: ^0.11.0+1
  kt_dart: ^0.7.0+1
  dio: ^3.0.10
  dio_http_cache: ^0.2.8
  flutter_hooks: ^0.13.1
  enum_to_string: ^1.0.9
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flushbar: ^1.10.4
  equatable: ^1.2.4
  json_annotation: ^3.0.1
  floor: ^0.14.0
  state_notifier: ^0.6.0
  flutter_state_notifier: ^0.6.1
  provider: ^4.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^1.2.1
  mockito: ^4.1.1
  bloc_test: ^7.0.1
  build_runner: ^1.10.0
  injectable_generator: ^1.0.4
  lint: ^1.2.0
  auto_route_generator: ^0.6.8
  freezed: ^0.11.5
  json_serializable: ^3.4.0
  floor_generator: ^0.14.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
