name: word_branches
description: A new Flutter project.
scripts:
  runner: flutter pub run build_runner build --delete-conflicting-outputs
  runner-watch: flutter pub run build_runner watch --delete-conflicting-outputs

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  auto_route: ^0.6.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  enum_to_string: ^1.0.14
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.15.0
  font_awesome_flutter: ^8.11.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  injectable: ^1.0.5
  kt_dart: ^0.8.0
  path: 1.8.0-nullsafety.3
  path_provider: ^1.6.24
  rxdart: ^0.25.0
  sembast: ^2.4.8+1
  stacked: ^1.7.7
  stacked_hooks: ^0.1.3+2
  stacked_services: ^0.6.0+1

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.11
  faker: ^1.3.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.6
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.1
  lint: ^1.5.1
  mockito: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
